Stubbing out the upgrade checking code. This goes off to the GitLab-CE repo and grabs the list of tags. If the connection fails (as has happened in EC) this throws a error like this:
Failures:

  1) Gitlab::Upgrader latest_version_raw should be latest version for GitLab 5
     Failure/Error: upgrader.latest_version_raw.should == "v5.4.2"
     NoMethodError:
       undefined method `match' for nil:NilClass
     # ./lib/gitlab/upgrader.rb:49:in `latest_version_raw'
     # ./spec/lib/gitlab/upgrader_spec.rb:21:in `block (3 levels) in <top (required)>'